### PR TITLE
Add certificate migration e2e test #131

### LINKED ISSUE #131: TLS Cert migration testing
At a high level, we need to verify the following workflows:

1 migrate customer from k8s CA signed certs to self signed certs
2 migrate customer from custom certs to self signed certs
3 migrate customer from self signed certs to custom certs
4 migrate customer from self signed certs to cert manager certs

Most of these can be validated manually, but I would pick either #2 or #3 and make a permanent test to make sure we don't break this functionality in the future.

### PR DESCRIPTION
**Pull request by abhishekdwivedi3060**
closes #131 
* Added migration test from "Bring Your Own Certificate" method to self-signer method

### CODE REVIEW

**Comment by udnay** [comment]
Looks like the failure might be legit
> UPGRADE FAILED: cannot patch "crdb-test-cockroachdb" with kind StatefulSet: StatefulSet.apps "crdb-test-cockroachdb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

**Comment by abhishekdwivedi3060** [comment]
The failure was because of a typo. Fixed that.

**Comment by abhishekdwivedi3060** [comment]
While upgrading, the default self-signer method is used and in the statefulset template condition, the node secret names are different for BYOC and self-signer based on the `.Values.tls.certs.selfSigner.enabled` . So IMO no need to delete the user provided secrets to test migration.

**Review by udnay — APPROVED** [review]
LGTM

**Pull request merged**
