### PR TITLE
Add custom fields to self signer jobs

### PR DESCRIPTION
**Pull request by 81887821**
Currently annotations, affinity, node selector and tolerations are only applied to self signer init job. It would be better if those are also applied to rotate cronjobs and clean-up job.
My use case is to disable Istio sidecar injection to the clean-up job.

### CODE REVIEW

**Comment by umi0410** [comment]
It will be great supporting both additional labels and annotations.
For your reference, the current related code is here: https://github.com/cockroachdb/helm-charts/blob/0cba0b68def62547888f52d6183a736af4c06292/cockroachdb/templates/job-cleaner.yaml#L20-L26

**Comment by 81887821** [comment]
Added support for labels

**Comment by udnay** [comment]
@prafull01 can you take a look at this please?

@81887821 can you please rebase with master?

**Review by prafull01 — APPROVED** [review]

**Comment by prafull01** [comment]
LGTM, Approved. @81887821 Please rebase again, so that I can merge this change.

**Pull request merged**
