### PR TITLE
set imagePullSecrets for all jobs and cronjobs using tls.selfSigner.image

### PR DESCRIPTION
**Pull request by JorritSalverda**
Fixes https://github.com/cockroachdb/helm-charts/issues/172

### CODE REVIEW

**Comment by JorritSalverda** [comment]
@keith-mcclellan is this okay to be merged? Anything you want me to change?

**Comment by JorritSalverda** [comment]
@DuskEagle any chance this can get merged?

**Comment by JorritSalverda** [comment]
As there currently are not tests checking the yaml properties itself I'm not sure how to add those. The tests in `cockroachdb_helm_template_test.go` only focus on verifying error messages if incompatible values are set.

**Comment by JorritSalverda** [comment]
@udnay any suggestion on how to add tests confirming the presence of certain properties when rendering templates?

**Comment by JorritSalverda** [comment]
@keith-mcclellan @DuskEagle @udnay could you please have another look at this?

**Comment by udnay** [comment]
@prafull01 can you take a look at this PR?

@JorritSalverda can you rebase and resolve the conflicts?

**Comment by JorritSalverda** [comment]
@prafull01 I've rebased and resolved conflicts (only in Chart.yaml). Let's see if it passes all tests.

**Comment by JorritSalverda** [comment]
@prafull01 What do you think?  Is this a flaky test failing?

**Pull request closed without merging**
