### PR TITLE
New logging configuration

### PR DESCRIPTION
**Pull request by sergeyshaykhullin**
# Problem
This needs to specify `--log` or `--log-config-file`. New logging api can't be used with old one

Details: https://github.com/cockroachdb/helm-charts/issues/103

# Changes
Do not append `--logtostderr` and add secret + mount + --log-config-path args if `.Values.log.enabled`

### CODE REVIEW

**Comment by Temikus** [comment]
Hey folks, this is blocking us a bit as ngrok parsing keeps breaking on corner cases - any way I can help move this along?

**Comment by 123BLiN** [comment]
In our case we need slow log with query time correctly parsed

**Comment by sergeyshaykhullin** [comment]
My next steps is to add cm for log config, mount it to all pods and pass log file path flag if enabled

It would be better and more... Native and transparent then operating on strings and do helm conversions

Also you will not have a very long logs config args on process start

But the main bottleneck is a review... I can't speed it up ;c

**Comment by udnay** [comment]
@sergeyshaykhullin can you add some test cases for this change please? You can see an example here https://github.com/cockroachdb/helm-charts/blob/master/tests/template/cockroachdb_helm_template_test.go

**Comment by sergeyshaykhullin** [comment]
@udnay Seems like done

**Review by udnay — APPROVED** [review]
LGTM

**Pull request merged**
