### PR TITLE
add ability to use extra volumes in statefulset

### LINKED ISSUE #182: allow to add extra volumes in cockroachdb pods
## Use case

We need to take backups of cockroachdb (like everybody spould) and export them to an external repository
For doing so we want to use tanzu/velero project.

## Analysis

Since there is no other volumes tahn datadir and certs there is not good candidate to dump the databases.
We could have been end up using datadir but this meens to sync also the real data files of cockroachdb which is both not needed and a ressource exausting

## Solution

We can allow to pass extra volumes to STS pods in order to have an easy way to backup our dbs
This can also be used for other use cases since this is quite a generic approach
Seems to be the way taken for a lot helm charts of the community, especially bitnami ones so it can be considered as a good practice

### PR DESCRIPTION
**Pull request by fredleger**
will fix #182

### CODE REVIEW

**Comment by fredleger** [comment]
ready to merge on my side

**Comment by fredleger** [comment]
any update on this one ? we do maintain a private fork of the helm chart just for it :-)

**Comment by udnay** [comment]
This looks fine to me, can you please add some tests for this though.

**Comment by fredleger** [comment]
one year happy bday !

**Pull request closed without merging**
