### PR TITLE
Add cockroachdb-ca-cert duration and renewal interval

### PR DESCRIPTION
**Pull request by mekaan**
Addresses the issue #397

### CODE REVIEW

**Comment by mekaan** [comment]
Att: @prafull01 (cc: @rail  )
PR is failing in the Linting stage with is just a git diff, when I try it, it works without any issue but I am not sure why it is failing. Can you help to resolve it?

**Comment by rail** [comment]
You can run `go run build/build.go generate` to update the generated files and the lint check should pass.

**Comment by mekaan** [comment]
Can I get an approval for the checks to run? @rail @prafull01

**Comment by mekaan** [comment]
Are we going to be able to merge this PR, It looks ready.  @rail @prafull01

**Comment by rail** [comment]
I'll let @prafull01 to chime in.

**Comment by mekaan** [comment]
Do we have any update about this @prafull01?

**Comment by mekaan** [comment]
Can we get someone else on this @rail? @prafull01 looks inactive for the last 3 months🤔

**Review by udnay — APPROVED** [review]
LGTM

**Comment by rail** [comment]
@mekaan thank you for your contribution and sorry for the delay!

**Comment by mekaan** [comment]
Thanks a lot 🥇

**Pull request merged**
