### PR TITLE
Fix link to Helm RBAC topic

### PR DESCRIPTION
**Pull request by kylos101**
The current link yields a 404 error. Does what I changed match your expectations?

### CODE REVIEW

**Comment by kenliu** [comment]
Hi @kylos101 thanks for your submission! Our team will review this PR next week. Happy 4th!

**Comment by jlinder** [comment]
Hi @kylos101 , Thanks for the PR. Yes, I believe that matches the expectation. If you would please increment the [chart version](https://github.com/kylos101/helm-charts/blob/patch-1/cockroachdb/Chart.yaml#L4) to 4.0.4, it'll be good to go.

**Comment by kylos101** [comment]
@jlinder all set, thank you for guidance and example link! That made it super easy.

**Comment by kylos101** [comment]
@jlinder this should be all set now, let me know if anything else is needed?

**Comment by jlinder** [comment]
Hi @kylos101 , I noticed the version on master was incremented in another commit. If you can increment the patch number to one greater than what's on master, I'll get it merged as soon as it's in so this doesn't happen again.

**Comment by kylos101** [comment]
@jlinder good catch! It should be better now. 👍

**Comment by jlinder** [comment]
Excellent. Thanks @kylos101 !

**Pull request merged**
