### PR TITLE
Add a e2e job and fix values.yaml for helm install

### PR DESCRIPTION
**Pull request by prafull01**
- Add a e2e jobs in CI
- Add a `gcr.io` registry and repository to install in helm chart

### CODE REVIEW

**Comment by prafull01** [comment]
@udnay Do we want to add different job for rotating the certs or should we cover those tests in the e2e job only?

These tests will run sequentially as the CRDB needs to be installed on kind cluster which has limited resources.

**Review by udnay — APPROVED** [review]
LGTM

**Comment by udnay** [comment]
We can split up the e2e tests into separate jobs, that's worked pretty well in the operator

**Comment by prafull01** [comment]
@udnay Okay, I will add another job when I will raise the rotate certificates test cases PR. Or you want me to add the job in this PR only? That job will fail until I raise the rotate certificates jobs PR.

**Comment by udnay** [comment]
A new PR is better so that we can try to get CI green

**Pull request merged**
