### PR TITLE
Revert to v21.1.7

### PR DESCRIPTION
**Pull request by celiala**

### CODE REVIEW

**Comment by celiala** [comment]
Not sure who the best person reviewer would be for downgrading a "latest" tag (pointing latest to an older CRDB version). Maybe @DuskEagle ?

**Review by joshimhoff — APPROVED** [review]
LGTM.

**Review by udnay — APPROVED** [review]
LGTM

**Comment by celiala** [comment]
TFTRs!

**Comment by sergeyshaykhullin** [comment]
@celiala Can you please add more details on why this revert is needed?

**Pull request merged**
