### PR TITLE
allow custom tlsConfig for serviceMonitor (#180)

### PR DESCRIPTION
**Pull request by fredleger**
Signed-off-by: Frederic Leger <frederic@webofmars.com>

### CODE REVIEW

**Comment by fredleger** [comment]
Ready to merge on my side

**Comment by manuelottlik** [comment]
Do you need any help getting this merged? I would like to see this feature implemented as well. What kind of tests were you thinking of? Seems like a pretty simple feature.

**Comment by DoGab** [comment]
Can we proceed on that? @udnay what tests are you expecting and what kind of examples?

**Comment by benjyiw** [comment]
The serviceMonitor in this helm chart is effectively useless without this configuration option because metrics run on https with a self-signed cert by default. Even if you did get a different cert onto the https endpoint, it wouldn't work because prometheus communicates by IP address. 

Can we please get this merged?

Linking the relevant issue because they aren't directly linked at the moment: https://github.com/cockroachdb/helm-charts/issues/180

**Comment by fredleger** [comment]
@udnay this is on your watch now, ever merge it or say in what it's invalid :-)

**Comment by fredleger** [comment]
dead project ?

**Comment by mmianl** [comment]
Hi @udnay 

This is still an issue, can we revive this PR or #141?

**Comment by DocuchCollabox** [comment]
Could you please merge this? This is an old issue and very simple fix

**Comment by prafull01** [comment]
Hey @DocuchCollabox 
I am maintaining this project and I am going to review these changes soon and update here.

**Pull request closed without merging**
